### ISSUE TITLE
Crashes zygote on boot with Android 15 

### ISSUE THREAD

**Issue by Buggen82** [neoblackxt/AnyWebView#21]
Crashes zygote on boot.
Pixel 9
Magisk 28.0
LsPosed_mod 1.9.3

**Comment by zihu12** [comment]
Tried to fix but with no luck
For one with ability/interest to fix, the following is my error log(don't know whether the author has the same case through):
```
Crash unexpectedly: java.lang.RuntimeException: Failed to create service com.android.server.webkit.WebViewUpdateService: service constructor threw an exception
 at com.android.server.SystemServiceManager.startService(SystemServiceManager.java:259)
 at com.android.server.SystemServer.startCoreServices(SystemServer.java:1527)
 at com.android.server.SystemServer.run(SystemServer.java:1017)
 at com.android.server.SystemServer.main(SystemServer.java:677)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:983)
Caused by: java.lang.reflect.InvocationTargetException
 at java.lang.reflect.Constructor.newInstance0(Native Method)
 at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
 at com.android.server.SystemServiceManager.startService(SystemServiceManager.java:248)
 ... 6 more
Caused by: android.util.AndroidRuntimeException: No available by default WebView Provider.
 at com.android.server.webkit.WebViewUpdateServiceImpl2.<init>(WebViewUpdateServiceImpl2.java:126)
 at com.android.server.webkit.WebViewUpdateService.<init>(WebViewUpdateService.java:76)
 ... 9 more
```

**Comment by XRevan86** [comment]
I personally switched from AnyWebView to Open WebView after concluding that the latter is infinitely easier to get working again.

**Comment by zihu12** [comment]
https://github.com/neoblackxt/AnyWebView/releases/tag/v1.3 works for me.
Don't know whether for you through.
